### ISSUE TITLE
Raster* distance() should handle conversion and resizing

### ISSUE THREAD

**Issue by marcusnaslund** [cogneco/ooc-kean#591] opened 2015-10-21 12:52 UTC
Right now, that part of `distance()` looks like this:
```ooc
// else if (!other instanceOf?(This))
// FIXME
// else if (this size != other size)
// FIXME
// else {
// ...
```
For the first case we have the `convertFrom` which can take care of the conversion.
For the second case we need to resize. Which one?
Or do we want to handle these special cases at all?

**Comment by davidhesselbom** [comment] 2015-10-21 12:58
Doubt it.

**Comment by marcusnaslund** [comment] 2015-10-22 09:45
@sebastianbaginski - you said to fix it in #561. Thoughts?

**Comment by sebastianbaginski** [comment] 2015-10-22 09:48
First case is easy to fix, so why not.
Second one, I don't know what's the theory behind this, let's maybe ask @bettinaselig ?

**Comment by davidhesselbom** [comment] 2015-10-22 10:06
IIRC `distance` was one of those things I converted from C# because "well, why not" and ended up not finishing it. It serves to compare an image created by a test to an existing "correct" image, in order to verify that some image processing function works as intended without having to manually investigate it. I'm not sure how relevant this is to the current project.

**Comment by marcusnaslund** [comment] 2015-11-03 10:24
Can someone make a decision on fix vs. remove?

**Comment by sebastianbaginski** [comment] 2015-11-03 13:44
We are using it currently in the Kean tests, for comparing the images without looking at them (as David mentioned already). Also, I will be fixing the first part of this issue if no one else is willing to.

**Comment by sebastianbaginski** [comment] 2015-11-03 13:45
Unless someone has a better idea for comparing the content of two images automatically, of course. Then we can remove it and implement this new algorithm.

**Comment by marcusnaslund** [comment] 2015-11-04 09:31
While you're at it, feel free to fix #574 :)

**Comment by sebastianbaginski** [comment] 2015-11-04 11:53
OK I will look into it.

**Comment by sebastianbaginski** [comment] 2015-11-12 07:01
https://github.com/cogneco/ooc-kean/pull/676 is merged.

**Closed by sebastianbaginski** 2015-11-12 07:01 UTC
Labels: enhancement, help wanted
